name: 下架商店中的包
title: "Remove package: {name}"
description: 移除发布到商店中的包，需要包的发布者提出该请求
labels: ["remove"]
body:
  - type: dropdown
    id: action
    attributes:
      label: 你想移除何种类型的包？
      options:
        - Plugin
        - Adapter
        - Bot
    validations:
      required: true

  - type: input
    id: pypi
    attributes:
      label: PyPI 项目名
      description: PyPI 项目名
      placeholder: e.g. nonebot-plugin-xxx
    validations:
      required: true

  - type: input
    id: module
    attributes:
      label: 插件 import 包名
      description: 插件 import 包名
      placeholder: e.g. nonebot_plugin_xxx
    validations:
      required: true
