name: 下架商店中发布的包
title: "Remove package: {name}"
description: 包的发布者可以提出议题，将会在审核通过后下架指定的包。
labels: ["remove"]
body:
  - type: input
    id: homepage
    attributes:
      label: 项目主页
      description: 
      placeholder: e.g. https://github.com/nonebot/nonebot-plugin-xxx
    validations:
      required: true
