name: CI

on:
  push:
    branches:
      - 'main'
      - 'dev'
  pull_request:
  release:
    types: [published]

jobs:
  test:
    name: Test
    runs-on: ubuntu-latest
    steps:
      - name: Docker meta
        id: docker_meta
        uses: crazy-max/ghaction-docker-meta@v1
        with:
          images: test/test
      - name: Dump TAGS context
        run: echo "$TAGS"
        env:
          TAGS: ${{ toJson(steps.docker_meta.outputs.tags) }}
