name: CI

on:
  push:
    branches:
      - 'main'
      - 'dev'
  pull_request:
  release:
    types: [published]

jobs:
  test:
    name: Test
    runs-on: ubuntu-latest
    outputs:
      version: ${{ steps.setVersion.outputs.version }}
    steps:
      - name: Dump GitHub context
        env:
          GITHUB_CONTEXT: ${{ toJson(github.event) }}
        run: echo "$GITHUB_CONTEXT"
      - name: Set version
        id: setVersion
        run: |
          if [[ "${{github.event_name}}" == "release" && "${{github.event.action}}" == "published" ]]; then
            echo "::set-output name=version::prod"
          else
            echo "::set-output name=version::dev"
          fi


  build:
    name: Build
    runs-on: ubuntu-latest
    needs: test
    steps:
      - name: Save version to file
        run: echo $VERSION > version.txt
        env:
          VERSION: ${{ needs.test.outputs.version }}
      - name: Upload version file
        uses: actions/upload-artifact@v2
        with:
          name: version
          path: ${{ github.workspace }}/version.txt

  deploy:
    name: Deploy
    runs-on: ubuntu-latest
    needs: build
    if: ${{ github.event_name == 'release' && github.event.action == 'published' }}
    steps:
      - name: Dump event_name
        env:
          EVENT_NAME: ${{ github.event_name }}
        run: echo "$EVENT_NAME"
      - name: Download all files
        uses: actions/download-artifact@v2
      - name: Display structure of downloaded files
        run: ls -R
