name: CI

on:
  push:
    branches:
      - 'main'
      - 'dev'
    tags:
      - 'v*'
  pull_request:

jobs:
  test:
    name: Test
    runs-on: ubuntu-latest
    steps:
      - name: Dump GitHub context
        env:
          GITHUB_CONTEXT: ${{ toJson(github.event) }}
        run: echo "$GITHUB_CONTEXT"
      - name: Save ref to file
        run: echo $REF > ref.txt
        env:
          REF: ${{ github.event.ref }}
      - name: Upload Ref file
        uses: actions/upload-artifact@v2
        with:
          name: ref
          path: ${{ github.workspace }}/ref.txt
