name: CI

on:
  push:
    branches:
      - 'main'
      - 'dev'
  pull_request:
  release:
    types: [published]

jobs:
  test:
    name: Test
    runs-on: ubuntu-latest
    steps:
      - name: Dump GitHub context
        env:
          GITHUB_CONTEXT: ${{ toJson(github.event) }}
        run: echo "$GITHUB_CONTEXT"
      - name: Save ref to file
        run: echo $REF > ref.txt
        env:
          REF: ${{ github.event.ref }}
      - name: Upload Ref file
        uses: actions/upload-artifact@v2
        with:
          name: ref
          path: ${{ github.workspace }}/ref.txt

  deploy:
    name: Deploy
    runs-on: ubuntu-latest
    needs: test
    if: ${{ github.event_name == 'release' && github.event.action == 'published' }}
    steps:
      - name: Dump event_name
        env:
          EVENT_NAME: ${{ github.event_name }}
        run: echo "$EVENT_NAME"
      - name: Download ref file
        uses: actions/download-artifact@v2
        with:
          name: ref
      - name: Display ref file
        run: cat ref.txt
      - name: Display folder
        run: ls
      - name: Copy file to server
        uses: Burnett01/rsync-deployments@4.1
        with:
          switches: -avzr --delete
          path: "*"
          remote_path: "actions/"
          remote_host: ${{ secrets.SSH_HOST }}
          remote_user: ${{ secrets.SSH_USERNAME }}
          remote_key: ${{ secrets.SSH_KEY }}
