name: 'Plugin Test'

on:
  pull_request:
    paths:
      - 'nonebot/**'

jobs:
  issue_bot:
    runs-on: ubuntu-latest
    name: plugin issue bot
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Set up Python 3.9
        uses: actions/setup-python@v2
        with:
          python-version: 3.9
      - name: Test
        run: |
          git diff origin/main..HEAD > diff
          cat diff
