name: 'NoneBot2 Store Test'

on:
  workflow_dispatch:
    inputs:
      offset:
        description: 'Offset'
        required: false
        default: '0'
      limit:
        description: 'Limit'
        required: false
        default: '1'

jobs:
  plugin_test:
    runs-on: ubuntu-latest
    name: nonebot2 plugin test
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          repository: nonebot/noneflow
          ref: fix/poetry-color
      - name: Install poetry
        if: ${{ !startsWith(github.event_name, 'pull_request') }}
        run: pipx install poetry
      - uses: actions/setup-python@v4
        with:
          python-version: "3.10"
      - name: Test Plugin
        id: plugin-test
        run: |
          poetry install
          poetry run python -m src.utils.store_test --offset ${{ github.event.inputs.offset }} --limit ${{ github.event.inputs.limit }} -f
      - name: Upload results
        uses: actions/upload-artifact@v3
        with:
          name: results
          path: |
            ${{ github.workspace }}/plugin_test/results.json
