name: Sync Repo

on:
  workflow_dispatch:

jobs:
  run:
    name: Sync-GitHub-to-Gitee
    runs-on: ubuntu-latest
    steps:
    - name: Mirror the Github repos to Gitee.
      uses: Yikun/hub-mirror-action@master
      with:
        src: github/he0119
        dst: gitee/he0119
        dst_key: ${{ secrets.GITEE_PRIVATE_KEY }}
        dst_token: ${{ secrets.GITEE_TOKEN }}
        force_update: true
        static_list: "smart-home,smart-home-flutter,smart-home-device,smart-home-deploy,CoolQBot,nonebot-plugin-datastore,nonebot-plugin-wordcloud"
